services:
  api:
    build: .
    container_name: entrevistatt_api_debug
    ports:
      - "8000:8000"
      - "5678:5678"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - .:/app
    
    env_file:
      - .env
    
    environment:
      - PYTHONUNBUFFERED=1
    
    # Debugpy envolviendo a Uvicorn (sin recarga automática para no romper el debugger)
    command: python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m uvicorn main:app --host 0.0.0.0 --port 8000