services:
  api:
    build: .
    container_name: entrevistatt_api_dev
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - .:/app
    
    env_file:
      - .env
    
    environment:
      - PYTHONUNBUFFERED=1
    
    # Servidor Uvicorn con recarga automática (hot reload)
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload