services:
  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile
      target: dev
      args:
        BASE_IMAGE: ghcr.io/entrevista-t/back:ml-base
    container_name: entrevistatt_api_dev
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ..:/app
      - pip-cache:/root/.cache/pip
      - hf-cache:/root/.cache/huggingface
    env_file:
      - ../.env
    environment:
      PYTHONUNBUFFERED: "1"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pip-cache:
  hf-cache: